### ISSUE TITLE
Undefined variable "shares" in individual-page-menu.phtml

### ISSUE THREAD

**Issue by hartenthaler** [06Games/Webtrees-ArgonLight#2]
Thank you! The screenshots are looking nice!

Now there is a new error  when activating your theme:
`Undefined variable: shares …/modules_v4/ArgonLight/resources/views/individual-page-menu.phtml:37
#0 …/modules_v4/ArgonLight/resources/views/individual-page-menu.phtml(37): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()`

**Comment by 06Games** [comment]
Glad you like the theme
The error must be due to the fact that I updated the theme to be compatible with Webtrees 2.1. (see [23228ec](https://github.com/06Games/Webtrees-ArgonLight/commit/23228ec2ef8db651dc6293376076433314113d4a))
If you are not using Webtrees version 2.1, I recommend you to use version 2.0 of this theme. [2a656d8](https://github.com/06Games/Webtrees-ArgonLight/tree/2a656d8497450e359d4d9f4f3d20fed39ab177bd)
You will then probably have the same problem as in #1. To solve it, just add between lines 2 and 3 of module.php :
```php
include "LightModule.php";
```

**Comment by hartenthaler** [comment]
I'm using 2.0.21 as my productive system (https://ahnen.hartenthaler.eu) and 2.1 as a test system. I will try both versions and report again.

**Comment by hartenthaler** [comment]
I cannot reproduce this error anymore.
